#!/usr/bin/env bash
# Results and logs default to this checkout so the script runs without the original
# /NAS mount; override with VITA_RESULTS_DIR / VITA_LOG_DIR. This is the same data dir
# the Python side anchors on (vita.utils.utils.DATA_DIR).
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${VITA_RESULTS_DIR:-$REPO_DIR/data/results}"
LOG_DIR="${VITA_LOG_DIR:-$REPO_DIR/data/logs}"
mkdir -p "$OUT_DIR" "$LOG_DIR"

# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/delivery_others_1" --language chinese --noise_category others --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original  > ${LOG_DIR}/run_gpt5_delivery_others_1.log 2>&1 
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/delivery_fault_1" --language chinese --noise_category fault --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original > ${LOG_DIR}/run_gpt5_delivery_fault_1.log 2>&1
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/delivery_incomplete_1" --language chinese --noise_category incomplete --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_delivery_incomplete_1.log 2>&1 
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/delivery_redundant_1" --language chinese --noise_category redundant --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_delivery_redundant_1.log 2>&1
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/delivery_induce_1" --language chinese --noise_category induce --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_delivery_induce_1.log 2>&1 

nohup vita run   --domain instore   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/instore_others_1" --language chinese --noise_category others --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original > ${LOG_DIR}/run_gpt5_instore_others_1.log 2>&1 
nohup vita run   --domain instore   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/instore_fault_1" --language chinese --noise_category fault --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original > ${LOG_DIR}/run_gpt5_instore_fault_1.log 2>&1
nohup vita run   --domain instore   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/instore_incomplete_1" --language chinese --noise_category incomplete --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_instore_incomplete_1.log 2>&1 
nohup vita run   --domain instore   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/instore_redundant_1" --language chinese --noise_category redundant --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_instore_redundant_1.log 2>&1
nohup vita run   --domain instore   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/instore_induce_1" --language chinese --noise_category induce --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_instore_induce_1.log 2>&1 

nohup vita run   --domain ota   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/ota_others_1" --language chinese --noise_category others --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original > ${LOG_DIR}/run_gpt5_ota_others_1.log 2>&1 
nohup vita run   --domain ota   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/ota_fault_1" --language chinese --noise_category fault --priority_level 5 --noise_nums 50 --max_single_tool_noise 1 --user_noise original > ${LOG_DIR}/run_gpt5_ota_fault_1.log 2>&1
nohup vita run   --domain ota   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/ota_incomplete_1" --language chinese --noise_category incomplete --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_ota_incomplete_1.log 2>&1 
nohup vita run   --domain ota   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1  --csv-output "${OUT_DIR}/ota_redundant_1" --language chinese --noise_category redundant --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_ota_redundant_1.log 2>&1
nohup vita run   --domain ota   --user-llm "gpt-4.1"   --agent-llm "gpt-4.1"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 1 --max-steps 300   --max-concurrency 1   --csv-output "${OUT_DIR}/ota_induce_1" --language chinese --noise_category induce --priority_level 5 --noise_nums 50 --max_single_tool_noise 10 --user_noise original > ${LOG_DIR}/run_gpt5_ota_induce_1.log 2>&1 

# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-5"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 20 --max-steps 300   --max-concurrency 10  --csv-output "${OUT_DIR}/delivery_induce_1" --language chinese --noise_category induce --priority_level 5 --noise_nums 6 --max_single_tool_noise 2 > ${LOG_DIR}/run_gpt5_induce.log 2>&1 
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-5"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 20 --max-steps 300   --max-concurrency 10   --csv-output "${OUT_DIR}/delivery_wrong_1" --language chinese --noise_category wrong --priority_level 5 --noise_nums 6 --max_single_tool_noise 2 > ${LOG_DIR}/run_gpt5_wrong.log 2>&1 
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-5"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 20 --max-steps 300   --max-concurrency 10   --csv-output "${OUT_DIR}/delivery_fault_1" --language chinese --noise_category fault --priority_level 5 --noise_nums 5 --max_single_tool_noise 1 > ${LOG_DIR}/run_gpt5_fault.log 2>&1 
# nohup vita run   --domain delivery   --user-llm "gpt-4.1"   --agent-llm "gpt-5"   --enable-think   --evaluator-llm "gpt-4o"   --num-trials 1   --num-tasks 20 --max-steps 300   --max-concurrency 10   --csv-output "${OUT_DIR}/delivery_incomplete_1" --language chinese --noise_category incomplete --priority_level 5 --noise_nums 5 --max_single_tool_noise 1 > ${LOG_DIR}/run_gpt5_incomplete.log 2>&1 